export const ERROR = 'error'
export const NO_AUTH = 'no-auth'
export const TOKEN = 'token'
export const SOCKET = 'socket'
export const SOCKET_ERROR = 'socket-error'
// global errors display
export const INITIALIZED = 'initialized'
export const ERRORS = 'errors'
export const LOADING = 'loading'
export const CONNECTED = 'connected'
export const ROOM = 'room'
export const CURRENT_ROOM = 'current-room'

export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const ME = 'me'
export const USERS = 'users'
export const CREATE_USER = 'create-user'
export const UPDATE_USER = 'update-user'
export const REMOVE_USER = 'remove-user'
